version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      monthly-updates:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
