/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('./components/ui/button/index').Button
  const Calendar: typeof import('./components/ui/calendar/index').Calendar
  const CalendarCell: typeof import('./components/ui/calendar/index').CalendarCell
  const CalendarCellTrigger: typeof import('./components/ui/calendar/index').CalendarCellTrigger
  const CalendarGrid: typeof import('./components/ui/calendar/index').CalendarGrid
  const CalendarGridBody: typeof import('./components/ui/calendar/index').CalendarGridBody
  const CalendarGridHead: typeof import('./components/ui/calendar/index').CalendarGridHead
  const CalendarGridRow: typeof import('./components/ui/calendar/index').CalendarGridRow
  const CalendarHeadCell: typeof import('./components/ui/calendar/index').CalendarHeadCell
  const CalendarHeader: typeof import('./components/ui/calendar/index').CalendarHeader
  const CalendarHeading: typeof import('./components/ui/calendar/index').CalendarHeading
  const CalendarNextButton: typeof import('./components/ui/calendar/index').CalendarNextButton
  const CalendarPrevButton: typeof import('./components/ui/calendar/index').CalendarPrevButton
  const DEADLINES_STORE_KEY: typeof import('./utils/constants').DEADLINES_STORE_KEY
  const DEFAULT_OPTIONS: typeof import('./utils/constants').DEFAULT_OPTIONS
  const DateUtils: typeof import('./utils/helpers').DateUtils
  const Dialog: typeof import('./components/ui/dialog/index').Dialog
  const DialogClose: typeof import('./components/ui/dialog/index').DialogClose
  const DialogContent: typeof import('./components/ui/dialog/index').DialogContent
  const DialogDescription: typeof import('./components/ui/dialog/index').DialogDescription
  const DialogFooter: typeof import('./components/ui/dialog/index').DialogFooter
  const DialogHeader: typeof import('./components/ui/dialog/index').DialogHeader
  const DialogOverlay: typeof import('./components/ui/dialog/index').DialogOverlay
  const DialogScrollContent: typeof import('./components/ui/dialog/index').DialogScrollContent
  const DialogTitle: typeof import('./components/ui/dialog/index').DialogTitle
  const DialogTrigger: typeof import('./components/ui/dialog/index').DialogTrigger
  const Drawer: typeof import('./components/ui/drawer/index').Drawer
  const DrawerClose: typeof import('./components/ui/drawer/index').DrawerClose
  const DrawerContent: typeof import('./components/ui/drawer/index').DrawerContent
  const DrawerDescription: typeof import('./components/ui/drawer/index').DrawerDescription
  const DrawerFooter: typeof import('./components/ui/drawer/index').DrawerFooter
  const DrawerHeader: typeof import('./components/ui/drawer/index').DrawerHeader
  const DrawerOverlay: typeof import('./components/ui/drawer/index').DrawerOverlay
  const DrawerTitle: typeof import('./components/ui/drawer/index').DrawerTitle
  const DrawerTrigger: typeof import('./components/ui/drawer/index').DrawerTrigger
  const Label: typeof import('./components/ui/label/index').Label
  const NativeSelect: typeof import('./components/ui/native-select/index').NativeSelect
  const NativeSelectOptGroup: typeof import('./components/ui/native-select/index').NativeSelectOptGroup
  const NativeSelectOption: typeof import('./components/ui/native-select/index').NativeSelectOption
  const OFFLINE_DB_KEY: typeof import('./utils/constants').OFFLINE_DB_KEY
  const ONBOARDING_DEADLINES: typeof import('./utils/constants').ONBOARDING_DEADLINES
  const OPTIONS_STORE_KEY: typeof import('./utils/constants').OPTIONS_STORE_KEY
  const Popover: typeof import('./components/ui/popover/index').Popover
  const PopoverAnchor: typeof import('./components/ui/popover/index').PopoverAnchor
  const PopoverContent: typeof import('./components/ui/popover/index').PopoverContent
  const PopoverTrigger: typeof import('./components/ui/popover/index').PopoverTrigger
  const Separator: typeof import('./components/ui/separator/index').Separator
  const Switch: typeof import('./components/ui/switch/index').Switch
  const Toaster: typeof import('./components/ui/sonner/index').Toaster
  const Tooltip: typeof import('./components/ui/tooltip/index').Tooltip
  const TooltipContent: typeof import('./components/ui/tooltip/index').TooltipContent
  const TooltipProvider: typeof import('./components/ui/tooltip/index').TooltipProvider
  const TooltipTrigger: typeof import('./components/ui/tooltip/index').TooltipTrigger
  const buttonVariants: typeof import('./components/ui/button/index').buttonVariants
  const circularAccess: typeof import('./utils/helpers').circularAccess
  const cn: typeof import('./lib/utils').cn
  const createPersistenceService: typeof import('./utils/persistence').createPersistenceService
  const deadlineItemSchema: typeof import('./utils/schema').deadlineItemSchema
  const hydrateAppStores: typeof import('./bootstrap').hydrateAppStores
  const persistence: typeof import('./utils/persistence').persistence
  const useDeadlines: typeof import('./composables/use-deadlines').default
  const useDeadlinesStore: typeof import('./stores/deadlines').useDeadlinesStore
  const useFile: typeof import('./composables/use-file').default
  const useOptions: typeof import('./composables/use-options').default
  const useOptionsStore: typeof import('./stores/options').useOptionsStore
  const useToast: typeof import('./composables/use-toast').default
}
// for type re-export
declare global {
  // @ts-ignore
  export type { PersistenceDriver } from './utils/persistence'
  import('./utils/persistence')
  // @ts-ignore
  export type { DatePickerModelValue, DeadlineItem, Options, DBResponseType } from './utils/types'
  import('./utils/types')
  // @ts-ignore
  export type { ButtonVariants } from './components/ui/button/index'
  import('./components/ui/button/index')
  // @ts-ignore
  export type { LayoutTypes } from './components/ui/calendar/index'
  import('./components/ui/calendar/index')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly Button: UnwrapRef<(typeof import('./components/ui/button/index'))['Button']>
    readonly Calendar: UnwrapRef<(typeof import('./components/ui/calendar/index'))['Calendar']>
    readonly CalendarCell: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarCell']
    >
    readonly CalendarCellTrigger: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarCellTrigger']
    >
    readonly CalendarGrid: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarGrid']
    >
    readonly CalendarGridBody: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarGridBody']
    >
    readonly CalendarGridHead: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarGridHead']
    >
    readonly CalendarGridRow: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarGridRow']
    >
    readonly CalendarHeadCell: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarHeadCell']
    >
    readonly CalendarHeader: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarHeader']
    >
    readonly CalendarHeading: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarHeading']
    >
    readonly CalendarNextButton: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarNextButton']
    >
    readonly CalendarPrevButton: UnwrapRef<
      (typeof import('./components/ui/calendar/index'))['CalendarPrevButton']
    >
    readonly DEADLINES_STORE_KEY: UnwrapRef<
      (typeof import('./utils/constants'))['DEADLINES_STORE_KEY']
    >
    readonly DEFAULT_OPTIONS: UnwrapRef<(typeof import('./utils/constants'))['DEFAULT_OPTIONS']>
    readonly DateUtils: UnwrapRef<(typeof import('./utils/helpers'))['DateUtils']>
    readonly Dialog: UnwrapRef<(typeof import('./components/ui/dialog/index'))['Dialog']>
    readonly DialogClose: UnwrapRef<(typeof import('./components/ui/dialog/index'))['DialogClose']>
    readonly DialogContent: UnwrapRef<
      (typeof import('./components/ui/dialog/index'))['DialogContent']
    >
    readonly DialogDescription: UnwrapRef<
      (typeof import('./components/ui/dialog/index'))['DialogDescription']
    >
    readonly DialogFooter: UnwrapRef<
      (typeof import('./components/ui/dialog/index'))['DialogFooter']
    >
    readonly DialogHeader: UnwrapRef<
      (typeof import('./components/ui/dialog/index'))['DialogHeader']
    >
    readonly DialogOverlay: UnwrapRef<
      (typeof import('./components/ui/dialog/index'))['DialogOverlay']
    >
    readonly DialogScrollContent: UnwrapRef<
      (typeof import('./components/ui/dialog/index'))['DialogScrollContent']
    >
    readonly DialogTitle: UnwrapRef<(typeof import('./components/ui/dialog/index'))['DialogTitle']>
    readonly DialogTrigger: UnwrapRef<
      (typeof import('./components/ui/dialog/index'))['DialogTrigger']
    >
    readonly Drawer: UnwrapRef<(typeof import('./components/ui/drawer/index'))['Drawer']>
    readonly DrawerClose: UnwrapRef<(typeof import('./components/ui/drawer/index'))['DrawerClose']>
    readonly DrawerContent: UnwrapRef<
      (typeof import('./components/ui/drawer/index'))['DrawerContent']
    >
    readonly DrawerDescription: UnwrapRef<
      (typeof import('./components/ui/drawer/index'))['DrawerDescription']
    >
    readonly DrawerFooter: UnwrapRef<
      (typeof import('./components/ui/drawer/index'))['DrawerFooter']
    >
    readonly DrawerHeader: UnwrapRef<
      (typeof import('./components/ui/drawer/index'))['DrawerHeader']
    >
    readonly DrawerOverlay: UnwrapRef<
      (typeof import('./components/ui/drawer/index'))['DrawerOverlay']
    >
    readonly DrawerTitle: UnwrapRef<(typeof import('./components/ui/drawer/index'))['DrawerTitle']>
    readonly DrawerTrigger: UnwrapRef<
      (typeof import('./components/ui/drawer/index'))['DrawerTrigger']
    >
    readonly Label: UnwrapRef<(typeof import('./components/ui/label/index'))['Label']>
    readonly NativeSelect: UnwrapRef<
      (typeof import('./components/ui/native-select/index'))['NativeSelect']
    >
    readonly NativeSelectOptGroup: UnwrapRef<
      (typeof import('./components/ui/native-select/index'))['NativeSelectOptGroup']
    >
    readonly NativeSelectOption: UnwrapRef<
      (typeof import('./components/ui/native-select/index'))['NativeSelectOption']
    >
    readonly OFFLINE_DB_KEY: UnwrapRef<(typeof import('./utils/constants'))['OFFLINE_DB_KEY']>
    readonly ONBOARDING_DEADLINES: UnwrapRef<
      (typeof import('./utils/constants'))['ONBOARDING_DEADLINES']
    >
    readonly OPTIONS_STORE_KEY: UnwrapRef<(typeof import('./utils/constants'))['OPTIONS_STORE_KEY']>
    readonly Popover: UnwrapRef<(typeof import('./components/ui/popover/index'))['Popover']>
    readonly PopoverAnchor: UnwrapRef<
      (typeof import('./components/ui/popover/index'))['PopoverAnchor']
    >
    readonly PopoverContent: UnwrapRef<
      (typeof import('./components/ui/popover/index'))['PopoverContent']
    >
    readonly PopoverTrigger: UnwrapRef<
      (typeof import('./components/ui/popover/index'))['PopoverTrigger']
    >
    readonly Separator: UnwrapRef<(typeof import('./components/ui/separator/index'))['Separator']>
    readonly Switch: UnwrapRef<(typeof import('./components/ui/switch/index'))['Switch']>
    readonly Toaster: UnwrapRef<(typeof import('./components/ui/sonner/index'))['Toaster']>
    readonly Tooltip: UnwrapRef<(typeof import('./components/ui/tooltip/index'))['Tooltip']>
    readonly TooltipContent: UnwrapRef<
      (typeof import('./components/ui/tooltip/index'))['TooltipContent']
    >
    readonly TooltipProvider: UnwrapRef<
      (typeof import('./components/ui/tooltip/index'))['TooltipProvider']
    >
    readonly TooltipTrigger: UnwrapRef<
      (typeof import('./components/ui/tooltip/index'))['TooltipTrigger']
    >
    readonly buttonVariants: UnwrapRef<
      (typeof import('./components/ui/button/index'))['buttonVariants']
    >
    readonly circularAccess: UnwrapRef<(typeof import('./utils/helpers'))['circularAccess']>
    readonly cn: UnwrapRef<(typeof import('./lib/utils'))['cn']>
    readonly createPersistenceService: UnwrapRef<
      (typeof import('./utils/persistence'))['createPersistenceService']
    >
    readonly deadlineItemSchema: UnwrapRef<(typeof import('./utils/schema'))['deadlineItemSchema']>
    readonly persistence: UnwrapRef<(typeof import('./utils/persistence'))['persistence']>
    readonly useDeadlines: UnwrapRef<(typeof import('./composables/use-deadlines'))['default']>
    readonly useDeadlinesStore: UnwrapRef<
      (typeof import('./stores/deadlines'))['useDeadlinesStore']
    >
    readonly useFile: UnwrapRef<(typeof import('./composables/use-file'))['default']>
    readonly useOptions: UnwrapRef<(typeof import('./composables/use-options'))['default']>
    readonly useOptionsStore: UnwrapRef<(typeof import('./stores/options'))['useOptionsStore']>
    readonly useToast: UnwrapRef<(typeof import('./composables/use-toast'))['default']>
  }
}
