/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAboutModal: typeof import('./components/modals/app-about-modal.vue')['default']
    AppConfirmationButton: typeof import('./components/app-confirmation-button.vue')['default']
    AppDatePicker: typeof import('./components/app-date-picker.vue')['default']
    AppDeadlineItem: typeof import('./components/app-deadline-item.vue')['default']
    AppDeadlineList: typeof import('./components/layout/app-deadline-list.vue')['default']
    AppHeader: typeof import('./components/layout/app-header.vue')['default']
    AppInput: typeof import('./components/layout/app-input.vue')['default']
    AppInputModal: typeof import('./components/modals/app-input-modal.vue')['default']
    AppModal: typeof import('./components/modals/app-modal.vue')['default']
    AppNavBar: typeof import('./components/layout/app-nav-bar.vue')['default']
    AppOptionsModal: typeof import('./components/modals/app-options-modal.vue')['default']
    AppScrollToTop: typeof import('./components/app-scroll-to-top.vue')['default']
    AppThemeToggle: typeof import('./components/app-theme-toggle.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Calendar: typeof import('./components/ui/calendar/Calendar.vue')['default']
    CalendarCell: typeof import('./components/ui/calendar/CalendarCell.vue')['default']
    CalendarCellTrigger: typeof import('./components/ui/calendar/CalendarCellTrigger.vue')['default']
    CalendarGrid: typeof import('./components/ui/calendar/CalendarGrid.vue')['default']
    CalendarGridBody: typeof import('./components/ui/calendar/CalendarGridBody.vue')['default']
    CalendarGridHead: typeof import('./components/ui/calendar/CalendarGridHead.vue')['default']
    CalendarGridRow: typeof import('./components/ui/calendar/CalendarGridRow.vue')['default']
    CalendarHeadCell: typeof import('./components/ui/calendar/CalendarHeadCell.vue')['default']
    CalendarHeader: typeof import('./components/ui/calendar/CalendarHeader.vue')['default']
    CalendarHeading: typeof import('./components/ui/calendar/CalendarHeading.vue')['default']
    CalendarNextButton: typeof import('./components/ui/calendar/CalendarNextButton.vue')['default']
    CalendarPrevButton: typeof import('./components/ui/calendar/CalendarPrevButton.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    Drawer: typeof import('./components/ui/drawer/Drawer.vue')['default']
    DrawerClose: typeof import('./components/ui/drawer/DrawerClose.vue')['default']
    DrawerContent: typeof import('./components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./components/ui/drawer/DrawerTitle.vue')['default']
    DrawerTrigger: typeof import('./components/ui/drawer/DrawerTrigger.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    NativeSelect: typeof import('./components/ui/native-select/NativeSelect.vue')['default']
    NativeSelectOptGroup: typeof import('./components/ui/native-select/NativeSelectOptGroup.vue')['default']
    NativeSelectOption: typeof import('./components/ui/native-select/NativeSelectOption.vue')['default']
    Popover: typeof import('./components/ui/popover/Popover.vue')['default']
    PopoverAnchor: typeof import('./components/ui/popover/PopoverAnchor.vue')['default']
    PopoverContent: typeof import('./components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./components/ui/popover/PopoverTrigger.vue')['default']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Sonner: typeof import('./components/ui/sonner/Sonner.vue')['default']
    Switch: typeof import('./components/ui/switch/Switch.vue')['default']
    Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
